map:
  width: 40  # 默认宽度
  height: 40  # 默认高度

start: [1, 1]  # 默认起点
goal: [18, 18]  # 默认终点

static_obstacles:  # 默认障碍物配置
  - [5, 5]
  - [5, 6]
  - [5, 7]
  - [6, 5]
  - [7, 5]
  - [8, 5]
  - [9, 5]
  - [10, 5]
  - [11, 5]
  - [12, 5]
  - [13, 5]
  - [14, 5]
  - [15, 5]
  - [16, 5]
  - [17, 5]
  - [18, 5]

car:  # 车辆属性
  speed: 1.0  # 速度 (m/s)
  length: 1.0  # 长度 (m)
  width: 1.0   # 宽度 (m)
